/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    testSum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HelloWorld_testSum
  (JNIEnv *, jobject, jint);

/*
 * Class:     HelloWorld
 * Method:    printArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_HelloWorld_printArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
