/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    testArraySum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_HelloWorld_testArraySum
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
