/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    testSum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HelloWorld_testSum
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
